require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AgendamentoDeVisitasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AgendamentoDeVisita. As you add validations to AgendamentoDeVisita, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AgendamentoDeVisitasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all agendamento_de_visitas as @agendamento_de_visitas" do
      agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:agendamento_de_visitas)).to eq([agendamento_de_visita])
    end
  end

  describe "GET show" do
    it "assigns the requested agendamento_de_visita as @agendamento_de_visita" do
      agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
      get :show, {:id => agendamento_de_visita.to_param}, valid_session
      expect(assigns(:agendamento_de_visita)).to eq(agendamento_de_visita)
    end
  end

  describe "GET new" do
    it "assigns a new agendamento_de_visita as @agendamento_de_visita" do
      get :new, {}, valid_session
      expect(assigns(:agendamento_de_visita)).to be_a_new(AgendamentoDeVisita)
    end
  end

  describe "GET edit" do
    it "assigns the requested agendamento_de_visita as @agendamento_de_visita" do
      agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
      get :edit, {:id => agendamento_de_visita.to_param}, valid_session
      expect(assigns(:agendamento_de_visita)).to eq(agendamento_de_visita)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AgendamentoDeVisita" do
        expect {
          post :create, {:agendamento_de_visita => valid_attributes}, valid_session
        }.to change(AgendamentoDeVisita, :count).by(1)
      end

      it "assigns a newly created agendamento_de_visita as @agendamento_de_visita" do
        post :create, {:agendamento_de_visita => valid_attributes}, valid_session
        expect(assigns(:agendamento_de_visita)).to be_a(AgendamentoDeVisita)
        expect(assigns(:agendamento_de_visita)).to be_persisted
      end

      it "redirects to the created agendamento_de_visita" do
        post :create, {:agendamento_de_visita => valid_attributes}, valid_session
        expect(response).to redirect_to(AgendamentoDeVisita.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agendamento_de_visita as @agendamento_de_visita" do
        post :create, {:agendamento_de_visita => invalid_attributes}, valid_session
        expect(assigns(:agendamento_de_visita)).to be_a_new(AgendamentoDeVisita)
      end

      it "re-renders the 'new' template" do
        post :create, {:agendamento_de_visita => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested agendamento_de_visita" do
        agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
        put :update, {:id => agendamento_de_visita.to_param, :agendamento_de_visita => new_attributes}, valid_session
        agendamento_de_visita.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested agendamento_de_visita as @agendamento_de_visita" do
        agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
        put :update, {:id => agendamento_de_visita.to_param, :agendamento_de_visita => valid_attributes}, valid_session
        expect(assigns(:agendamento_de_visita)).to eq(agendamento_de_visita)
      end

      it "redirects to the agendamento_de_visita" do
        agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
        put :update, {:id => agendamento_de_visita.to_param, :agendamento_de_visita => valid_attributes}, valid_session
        expect(response).to redirect_to(agendamento_de_visita)
      end
    end

    describe "with invalid params" do
      it "assigns the agendamento_de_visita as @agendamento_de_visita" do
        agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
        put :update, {:id => agendamento_de_visita.to_param, :agendamento_de_visita => invalid_attributes}, valid_session
        expect(assigns(:agendamento_de_visita)).to eq(agendamento_de_visita)
      end

      it "re-renders the 'edit' template" do
        agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
        put :update, {:id => agendamento_de_visita.to_param, :agendamento_de_visita => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agendamento_de_visita" do
      agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
      expect {
        delete :destroy, {:id => agendamento_de_visita.to_param}, valid_session
      }.to change(AgendamentoDeVisita, :count).by(-1)
    end

    it "redirects to the agendamento_de_visitas list" do
      agendamento_de_visita = AgendamentoDeVisita.create! valid_attributes
      delete :destroy, {:id => agendamento_de_visita.to_param}, valid_session
      expect(response).to redirect_to(agendamento_de_visitas_url)
    end
  end

end
