require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TipoDeImovelsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TipoDeImovel. As you add validations to TipoDeImovel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipoDeImovelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tipo_de_imovels as @tipo_de_imovels" do
      tipo_de_imovel = TipoDeImovel.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tipo_de_imovels)).to eq([tipo_de_imovel])
    end
  end

  describe "GET show" do
    it "assigns the requested tipo_de_imovel as @tipo_de_imovel" do
      tipo_de_imovel = TipoDeImovel.create! valid_attributes
      get :show, {:id => tipo_de_imovel.to_param}, valid_session
      expect(assigns(:tipo_de_imovel)).to eq(tipo_de_imovel)
    end
  end

  describe "GET new" do
    it "assigns a new tipo_de_imovel as @tipo_de_imovel" do
      get :new, {}, valid_session
      expect(assigns(:tipo_de_imovel)).to be_a_new(TipoDeImovel)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipo_de_imovel as @tipo_de_imovel" do
      tipo_de_imovel = TipoDeImovel.create! valid_attributes
      get :edit, {:id => tipo_de_imovel.to_param}, valid_session
      expect(assigns(:tipo_de_imovel)).to eq(tipo_de_imovel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TipoDeImovel" do
        expect {
          post :create, {:tipo_de_imovel => valid_attributes}, valid_session
        }.to change(TipoDeImovel, :count).by(1)
      end

      it "assigns a newly created tipo_de_imovel as @tipo_de_imovel" do
        post :create, {:tipo_de_imovel => valid_attributes}, valid_session
        expect(assigns(:tipo_de_imovel)).to be_a(TipoDeImovel)
        expect(assigns(:tipo_de_imovel)).to be_persisted
      end

      it "redirects to the created tipo_de_imovel" do
        post :create, {:tipo_de_imovel => valid_attributes}, valid_session
        expect(response).to redirect_to(TipoDeImovel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipo_de_imovel as @tipo_de_imovel" do
        post :create, {:tipo_de_imovel => invalid_attributes}, valid_session
        expect(assigns(:tipo_de_imovel)).to be_a_new(TipoDeImovel)
      end

      it "re-renders the 'new' template" do
        post :create, {:tipo_de_imovel => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tipo_de_imovel" do
        tipo_de_imovel = TipoDeImovel.create! valid_attributes
        put :update, {:id => tipo_de_imovel.to_param, :tipo_de_imovel => new_attributes}, valid_session
        tipo_de_imovel.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested tipo_de_imovel as @tipo_de_imovel" do
        tipo_de_imovel = TipoDeImovel.create! valid_attributes
        put :update, {:id => tipo_de_imovel.to_param, :tipo_de_imovel => valid_attributes}, valid_session
        expect(assigns(:tipo_de_imovel)).to eq(tipo_de_imovel)
      end

      it "redirects to the tipo_de_imovel" do
        tipo_de_imovel = TipoDeImovel.create! valid_attributes
        put :update, {:id => tipo_de_imovel.to_param, :tipo_de_imovel => valid_attributes}, valid_session
        expect(response).to redirect_to(tipo_de_imovel)
      end
    end

    describe "with invalid params" do
      it "assigns the tipo_de_imovel as @tipo_de_imovel" do
        tipo_de_imovel = TipoDeImovel.create! valid_attributes
        put :update, {:id => tipo_de_imovel.to_param, :tipo_de_imovel => invalid_attributes}, valid_session
        expect(assigns(:tipo_de_imovel)).to eq(tipo_de_imovel)
      end

      it "re-renders the 'edit' template" do
        tipo_de_imovel = TipoDeImovel.create! valid_attributes
        put :update, {:id => tipo_de_imovel.to_param, :tipo_de_imovel => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipo_de_imovel" do
      tipo_de_imovel = TipoDeImovel.create! valid_attributes
      expect {
        delete :destroy, {:id => tipo_de_imovel.to_param}, valid_session
      }.to change(TipoDeImovel, :count).by(-1)
    end

    it "redirects to the tipo_de_imovels list" do
      tipo_de_imovel = TipoDeImovel.create! valid_attributes
      delete :destroy, {:id => tipo_de_imovel.to_param}, valid_session
      expect(response).to redirect_to(tipo_de_imovels_url)
    end
  end

end
